name: Yum Update
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: yum-update.yml
          directory: ./
          key: ${{secrets.SSH_KEY}}
          options: |
            --verbose

